import './globals.css'
import AppBgImg from "./AppBgImg"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppBgImg/>
        {children}
      </body>
    </html>
  )
}
